version: '3.7'
networks:
  default:
    name: mcloud
services:
  appium:
    image: "public.ecr.aws/zebrunner/appium:2.0.5"
    container_name: "appium"
    ports:
      - "4723:4723"
    env_file:
      - appium.env
    volumes:
      - "appium-storage-volume:/opt/appium-storage"
      - "device-volume:/tmp/log"
    restart: on-failure

  uploader:
    image: "public.ecr.aws/zebrunner/uploader:3.2"
    container_name: "uploader"
    env_file:
      - s3.env
    volumes:
      - "device-volume:/tmp/log"
    restart: on-failure

  stf:
    image: "public.ecr.aws/zebrunner/mcloud-device:2.5.2"
    container_name: "device"
    ports:
      - "7400-7410:7400-7410"
    env_file:
      - stf.env
    deploy:
      resources:
        limits:
          memory: 1g
    logging:
      options:
        max-size: 50m
    links:
      - "appium:appium"
      - "redroid:redroid"
    restart: on-failure

  redroid:
    image: "public.ecr.aws/zebrunner/redroid:13.0.0"
    container_name: "redroid"
    ports:
      - "5555:5555"
    privileged: true
    command: "androidboot.use_memfd=1"
    volumes:
      - "redroid-volume:/tmp/log"
    restart: on-failure

volumes:
  appium-storage-volume: null
  device-volume: null
  redroid-volume: null
