version: '3.7'
networks:
  default:
    name: mcloud
services:
  connector:
    image: "${ANDROID_CONNECTOR_IMAGE}:${ANDROID_CONNECTOR_VERSION}"
    container_name: "connector"
    env_file:
      - connector.env
    volumes:
      - "device-volume:/tmp/log"
    restart: on-failure

  uploader:
    image: "${UPLOADER_IMAGE}:${UPLOADER_VERSION}"
    container_name: "uploader"
    env_file:
      - s3.env
    volumes:
      - "device-volume:/tmp/log"
    restart: on-failure

  stf:
    image: "${DEVICE_IMAGE}:${DEVICE_VERSION}"
    container_name: "device"
    ports:
      - "7400-7410:7400-7410"
    env_file:
      - stf.env
    deploy:
      resources:
        limits:
          memory: 1g
    logging:
      options:
        max-size: 50m
    links:
      - "connector:connector"
    restart: on-failure

  appium:
    image: "${APPIUM_IMAGE}:${APPIUM_VERSION}"
    container_name: "appium"
    ports:
      - "4723:4723"
    env_file:
      - appium.env
    volumes:
      - "appium-storage-volume:/opt/appium-storage"
      - "device-volume:/tmp/log"
    links:
      - "connector:connector"
      - "device:device"
    restart: on-failure

  redroid:
    image: "${REDROID_IMAGE}:${REDROID_VERSION}"
    container_name: "redroid"
    ports:
      - "5555:5555"
    privileged: true
    command: "androidboot.use_memfd=1"
    volumes:
      - "redroid-volume:/tmp/log"
    restart: on-failure

volumes:
  appium-storage-volume: null
  device-volume: null
  redroid-volume: null
